### ISSUE TITLE
Help with inline_keyboard

### ISSUE THREAD

**Issue by juanruiz85** [davtur19/TuriBot#1]
Hi

Do you can help me to do that when i selected a button this make an action please?

but the action will be after i choose an option

thank you

**Comment by NicMan37** [comment]
do you mean that after pressing a button you see other buttons?

**Comment by juanruiz85** [comment]
not really, I need when I press a button telegram is going to send me the information

example i will have a button called "Test" then when i pressed the button telegram is going to sent a message with the text "Test" to me

thank you

**Comment by juanruiz85** [comment]
The sample code shows three buttons, but when I press a button nothing happens

![image](https://user-images.githubusercontent.com/6697786/34495022-7f698396-efb0-11e7-9e59-c84c2a767c21.png)

**Comment by davtur19** [comment]
I just did a test, without making any changes to the code, if I press the first button the text of the message changes to "Button 1".
Did you make any changes to commands.php?

**Comment by juanruiz85** [comment]
hi
i download a fresh copy and the same happened, not work the buttons :(

maybe i have a something wrong and because of this cannot be edited the messages? I mean that when if I edited a message nothing happened and i think that should show a text when i edited a message or not?

Do I need to config something on the bot?

thank you

**Comment by davtur19** [comment]
The only configuration I made yesterday was to set up the webhook

You could try to change the code to line 72 in commands.php like this:

$r1 = answerCallbackQuery($id, "Button 1");
$r2 = editMessageText("Button 1",$message_chat_id, $message_message_id, NULL, NULL, NULL, $menu);
$r1 = json_encode($r1, true);
$r2 = json_encode($r2, true);
sendMessage(11111111, "Debug1: $r1");
sendMessage(11111111, "Debug2: $r2");
//replace 111111111 with your telegram id

after changing it, try pressing the button and send me what you are sent to chat

**Comment by juanruiz85** [comment]
i made the change but nothing happened
![image](https://user-images.githubusercontent.com/6697786/34575101-c9ba04b6-f136-11e7-812e-506a87ab8320.png)
![image](https://user-images.githubusercontent.com/6697786/34575126-dc1dcd4a-f136-11e7-92d7-3c737ca7bc90.png)

**Comment by davtur19** [comment]
You do not need to activate it
I can not replicate the problem.
Are you able to use postman for a better debug?

**Comment by davtur19** [comment]
Try changing the bot.php file and saving the $input variable to a file.
then try to send a message, after, inside the file, you should find the update that sent you the Telegram server
Then delete the file and press the button, if the file is empty, it means that the updates from the Telegram of the inline buttons do not arrive
If it does not receive the updates, try revoking the token and resetting the webhook

**Comment by juanruiz85** [comment]
hi
sorry was something about telegram, i revoked the token and now is working 👍 
and thank you for the idea of the write a file...now i have a log system on my telegram bot
really thank you for your help

![image](https://user-images.githubusercontent.com/6697786/34594361-ccac73b4-f18d-11e7-8649-91cd7d2f6b7e.png)

**Comment by davtur19** [comment]
Don't worry, it's rarely Telegram's fault
