### ISSUE TITLE
Issue: ❓ Support Question

### ISSUE THREAD

**Issue by Theolodewijk** [davtur19/TuriBot#10]
I tray to get some info bot Telegram don't reply support tickets!

Can you help me with Telegram. so that I am sent in the right direction.

I work for a government organization and we have a weekly exercise, now I would like to simplify this with, for example, a poll or something else where if someone responds to that I get a feedback via the telegram API.

I want to use PHP for this but see many options on the Telegram website https://core.telegram.org/bots/samples#php but now which one is and is not suitable for this and there is a little explanation somewhere how to find it tackles this?

https://telegram.org/blog/polls-2-0-vmq

Greetings Theo

**Comment by MarcoBuster** [comment]
What government do you work for?

**Comment by Theolodewijk** [comment]
> What government do you work for?

fire department in the Netherlands

**Comment by MarcoBuster** [comment]
We don't really understand your question. Can you rewrite it in a better english? (I don't want to be rude)

**Comment by Theolodewijk** [comment]
I want to make something where members in a group can respond to an activity that we have every week. if someone responds that I can see with the api who has responded in the group to that activity.


hopefully this is a little clearer what I want to do with Telegram.

**Comment by lausek** [comment]
Hi @Theolodewijk, here are some pointers for you:

1. There are [Inline Keyboards](https://core.telegram.org/bots/api#inlinekeyboardmarkup), basically buttons attached to a message.
    - A special parameter *callback_data* will be set inside a Telegram request whenever someone responded to that message.
2. You can setup a cron job - either on the local machine or as a [webservice](https://cron-job.org/en/) that will trigger a message after a given time.
    - You'll need the corresponding chat id for manually creating messages inside your group. You can get it by catching it out of previous messages to your bot.

Hope that helps! I'm voting to close this issue as it is not really related to this project.
