### ISSUE TITLE
How to use the $reply_markup var

### ISSUE THREAD

**Issue by duub** [davtur19/TuriBot#11]
Hi,
I want to use the $reply_markup var on sendMessage method to force a reply, but I don't know how to put there in a nice form... any help would be very apreciated!

It worked with this code below... but... not sure if I could type it nicely...

```
$client->sendMessage($chat_id, "Type something?", null, null, null, null,array(
          'force_reply_keyboard' => true ) )
```

I'm trying to implement a step-by-step proces... any example of how to do it? The force_reply isn't exactly what i wanted...

P.S.: Thanks for the work with this code!

**Comment by davtur19** [comment]
I didn't understand exactly what you want to do, in any case the [force reply](https://core.telegram.org/bots/api#forcereply) should be used like this:
```php
$client->sendMessage($chat_id, "text", null, null, null, null, ["force_reply" => true]);
```

**Comment by duub** [comment]
Thanks for the clarification!
I want to do something similar to a menu with several options and a sequence of questions in each option...

**Comment by davtur19** [comment]
Have you already seen the examples?
https://github.com/davtur19/TuriBot/blob/master/examples/webhook.php#L32

**Comment by duub** [comment]
Yes, it is a good starting point, but still don't know how to ask for an ID, keep that value and then ask for another value keeping both values related as a connected answer, so finally store these values to a database.

**Comment by duub** [comment]
Seems that the only way to store data between messages is using a database
