### ISSUE TITLE
Recuperare Live Location

### ISSUE THREAD

**Issue by swim89** [davtur19/TuriBot#2]
Ciao, avrei la necessità, sul bot, di memorizzare latitude e longitude della LiveLocation.

Io sul bot invio la mia posizione e vorrei che questa, ogni volta che lui ne invia una aggiornata, se la memorizzasse su un file, un db, ecc...

Sai spiegarmi come fare?

**Comment by davtur19** [comment]
Non sai come salvare su un file?
