### ISSUE TITLE
how do i get people's id via new chat member?

### ISSUE THREAD

**Issue by TravisScottex** [davtur19/TuriBot#22]
i tried this but it doesn't work

```
if (isset($update->message) or isset($update->edited_message)) {
    $chat_id = $client->easy->chat_id;
    $newuser = $client->easy->new_chat_members->user->id;

    if ($newuser and $chat_id == "channel id") {
        $client->sendMessage(my id, "test");
    }

}
```

**Comment by davtur19** [comment]
By default EasyVars only supports these variables: https://github.com/davtur19/TuriBot/blob/master/src/EasyVars.php#L7

If you want to use other variables you can extend the class as in the new examples:
1. https://github.com/davtur19/TuriBot/blob/async/examples/EasyVarsExt.php
1. https://github.com/davtur19/TuriBot/blob/async/examples/getUpdates.php#L10-L17

Or you can get the variable directly from `$update`
```php 
$update->message->new_chat_members;
```
Note that this only counts for `message`, if it is another type of update, such as `channel_post`, you will have to do:
```php 
$update->channel_post->new_chat_members;
```

More information about the updates: https://core.telegram.org/bots/api#update

**Comment by TravisScottex** [comment]
thanks, you were very clear :)
