### ISSUE TITLE
Why is it disabling all the permissions in the group?

### ISSUE THREAD

**Issue by Nik401** [davtur19/TuriBot#26]
I used this line to disable only "Send Messages" permission, but it disables all permissions in the group. What is wrong with the code?

`{
  "chat_id": {lv=Channel ID},
  "permissions": {"can_send_messages": false},  "use_independent_chat_permissions": false
}`

**Comment by davtur19** [comment]
I think if you don't specify a parameter the default is false, try specifying everything to true except what you want to set to false.

**Comment by Nik401** [comment]
Let me check. 😊

**Comment by Nik401** [comment]
So should I also use the `use_independent_chat_permissions` command?

**Comment by Nik401** [comment]
Wow, it's working! Thank you so much. 😊
