### ISSUE TITLE
help !! bots not running on both of my servers !

### ISSUE THREAD

**Issue by mrbeandev** [davtur19/TuriBot#27]
none of my bots are running 
i have 2 server with bots and both are not getting reply , why so ?

i am using php8.1 and latest `composer update` was done , yet i am getting no response in my bot , i am using the example code given in your github page

**Comment by davtur19** [comment]
With the latest update to 7.0 they changed the order of some of the parameters to be as similar as possible with the Bot API documentation

https://github.com/davtur19/TuriBot/commit/b4f7f0100d1926059d8aaca53250f47d06cd9e10

The examples with webhook may not have been updated, the one with getupdate I am sure it works.

I need more details to be able to help you.

**Comment by mrbeandev** [comment]
my file_system :
![image](https://github.com/davtur19/TuriBot/assets/34623886/12e3b6fc-78e5-46bf-977d-77cb7f760934)

i have used that code form getUpdates.php 
![image](https://github.com/davtur19/TuriBot/assets/34623886/9557ebc2-a0af-4b37-b3d3-4215f5dffa9a)

this is only a test bot so no need to worry about the token reveal ;/

my php version used in the nginx server is 
![image](https://github.com/davtur19/TuriBot/assets/34623886/79635f4a-2bc3-4f88-b038-ddf68aef7d3b)

php8.1-curl is installed and up-to-date

bot not responding :: 

![image](https://github.com/davtur19/TuriBot/assets/34623886/d6512776-1909-4099-bfe9-224d5388a7e3)


i waited for some time for telegram server to catch all updates but its been 20 minutes and no reply till now

**Comment by mrbeandev** [comment]
and my server says

````
root@john:/var/www/chicken/botx# curl --tlsv1.2 -v https://api.telegram.org
*   Trying 2001:67c:4e8:f004::9:443...
* Connected to api.telegram.org (2001:67c:4e8:f004::9) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to api.telegram.org:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to api.telegram.org:443 
root@john:/var/www/chicken/botx#
````

**Comment by davtur19** [comment]
It seems related to a problem with your connection and not PHP.

Try forcing ipv4 in curl with --ipv4

ipv6 should work on Bot API but certain IPs are banned.

If you don't mind using ipv6 you could disable it on your machine, online is full of guides on how to proceed.
Otherwise you could force php to use it with some curl settings.
