### ISSUE TITLE
mistakes in example

### ISSUE THREAD

**Issue by ahu** [davtur19/TuriBot#28]
https://github.com/davtur19/TuriBot/blob/14aff5e8054a0d8bfb8e5c2e579c93488c150e28/examples/webhook.php#L27

should be
```
$client->forwardMessage($chat_id, $chat_id, $message_id);
```

https://github.com/davtur19/TuriBot/blob/14aff5e8054a0d8bfb8e5c2e579c93488c150e28/examples/webhook.php#L29

should be
```
 $client->sendPhoto($chat_id, $client->inputFile("TuriPixel.png"));
```

https://github.com/davtur19/TuriBot/blob/14aff5e8054a0d8bfb8e5c2e579c93488c150e28/examples/webhook.php#L88

should be
```
$client->editMessageText("Button 1", $message_chat_id, $message_message_id, null, null, null, null, $menu);
```

also line 91 & line 94

**Comment by davtur19** [comment]
Thank you for opening the issue and reporting the bug
