### ISSUE TITLE
Inline keyboard problem

### ISSUE THREAD

**Issue by MarcoMihaiCondrache** [davtur19/TuriBot#4]
As the title suggest i have a problem with the inline keyboard.
When the i set a button function to url sendMessage return error 400 but if i change it to callback_data it works

`$menu["inline_keyboard"] = [
            [
                [
                    "text" => "e",
                    "url" => "ds",
                ],
            ],
            [
                [
                    "text"          => "IPTV",
                    "callback_data" => "startHELP",
                ],
                [
                    "text"          => "TUTORIAL 🔠",
                    "callback_data" => "startHELP",
                ],
                [
                    "text"          => "MEGAFLIX",
                    "callback_data" => "startHELP",
                ],
            ],
            [
                [
                    "text"          => "🅾️ PROPONI SERIE",
                    "callback_data" => "startSERIE",
                ],
                [
                    "text"          => "PROPONI FILM 🅾️",
                    "callback_data" => "startFILM",
                ],
            ],
            [
                [
                    "text"          => "I NOSTRI CANALI 🌐",
                    "callback_data" => "startHELP",
                ],
            ],
            [
                [
                    "text"          => "ABBONAMENTO",
                    "callback_data" => "startHELP",
                ],
            ],
        ];`

**Comment by davtur19** [comment]
https://core.telegram.org/bots/api#inlinekeyboardbutton

You must use `url` or `callback_query` 

- `url`
HTTP or tg:// url to be opened when button is pressed
- `callbackquery`
Data to be sent in a callback query to the bot when button is pressed, 1-64 bytes
