### ISSUE TITLE
null is not an instance of stdClass

### ISSUE THREAD

**Issue by lausek** [davtur19/TuriBot#7]
`Client->getUpdate()` could return null through `json_decode` which leads to this fatal error:

```
Fatal error: Uncaught TypeError: Return value of TuriBot\Client::getUpdate() must be 
an instance of stdClass, null returned in turibot/src/Client.php:46
```

PHP version: 7.3.13
Possible solution: Add nullable or remove type hint

**Comment by davtur19** [comment]
I could do a fix as you say, but the problem would remain, it should not return null.
Can you understand why the json decode goes wrong?
You may have [this](https://stackoverflow.com/questions/689185/json-decode-returns-null-after-webservice-call) problem
If you can, see with [json_last_error](https://www.php.net/manual/en/function.json-last-error.php) what error it gives you

**Comment by lausek** [comment]
No, I'm just calling the hook by myself so the input stream is empty. Anyways, the function should not panic.

What would be the value of `getUpdate` if the decoding wasn't successful?

**Comment by davtur19** [comment]
The return value of getUpdate could simply be a null, what do you think about it?

**Comment by lausek** [comment]
Yeah, think so too. That's why I created a pull request.
