### ISSUE TITLE
Bot token and $_GET["api"]

### ISSUE THREAD

**Issue by venkycc** [davtur19/TuriBot#9]
Hi 

Thanks for this !

Please update the documentation...where does one update the Bottoken from Botfather and in the case of the webhook, there is no API in the get request right?

Please clarify

Thanks

**Comment by davtur19** [comment]
Take a look at the new readme: https://github.com/davtur19/TuriBot#webhook

**Comment by venkycc** [comment]
Thank you...

There is an error: I will try to look at your class files later but if you can have a look, I'd really appreciate it: (autoload is installed via composer and included)

`    $api = $_POST["api"];
    $link = strip_tags($_POST["link"]);
    $connections = $_POST["connections"];
    $link = $link . "?api=" . $api;
Fatal error: Uncaught Error: Class 'TuriBot\Client' not found `

**Comment by davtur19** [comment]
Make sure you have everything up to date, and if the require is correct, I've put an example below of how it should look

```sh
ubuntu@scw-turi-ubuntu:~/test$ head setupWebhook.php
<?php

require_once __DIR__ . "/vendor/autoload.php";

use TuriBot\Client;


if (!function_exists("curl_version")) {
    exit("You must install or enable php-curl");
}
ubuntu@scw-turi-ubuntu:~/test$ ls
composer.json  composer.lock  setupWebhook.php  vendor
```
